[tool.ruff]
# Target Python version
target-version = "py311"
line-length = 220

[tool.ruff.lint]
# Enable Pyflakes (`F`), pycodestyle (`E`, `W`), isort (`I`)
select = ["E", "F", "I", "W"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
# The mypy configuration
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_calls = true
# Add this line to exclude the tests directory
exclude = ["aiecommerce/tests/", "venv/"]

[tool.django-stubs]
django_settings_module = "aiecommerce.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "aiecommerce.settings"
python_files = [
  "tests.py",
  "test_*.py",
  "*_tests.py",
]
